### ISSUE TITLE
How do i use with multiple entries?

### ISSUE THREAD

**Issue by afgoulart** [getjs/gulp-hot-reload#3]
```
TypeError: config.entry.unshift is not a function
    at createWebpackCompiler (/Users/afgoulart/projetos/my-project/node_modules/gulp-hot-reload/src/framework.js:18:16)
    at Object.enableHotReload (/Users/afgoulart/projetos/my-project/node_modules/gulp-hot-reload/src/framework.js:29:30)
    at init (/Users/afgoulart/projetos/my-project/node_modules/gulp-hot-reload/src/index.js:70:8)
    at /Users/afgoulart/projetos/my-project/node_modules/gulp-hot-reload/src/index.js:41:7
    at Gulp.module.exports (webpack-dev-server.js:28:11)
    at module.exports (/Users/afgoulart/projetos/my-project/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/afgoulart/projetos/my-project/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/afgoulart/projetos/my-project/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/afgoulart/projetos/my-project/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/afgoulart/projetos/my-project/node_modules/gulp/bin/gulp.js:129:20
```

**Comment by gone369** [comment]
I just created a new [pull request](https://github.com/getjs/gulp-hot-reload/pull/4) to fix this problem.

**Comment by afgoulart** [comment]
Thanks
